tokenizer:
  model_name: t5-small
  #model_name: Hydroflu/t5_small_retrained
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: False

reward_fn:
  #id: cos_similarity
  id: bleu

datapool:
  id: alpaca_gpt4
  #id: narrative_qa



env:
  #n_envs: 10
  n_envs: 1
  args:
    # max_prompt_length: 512
    # max_episode_length: 100
    # max_prompt_length: 256
    max_prompt_length: 128
    max_episode_length: 50
    terminate_on_eos: True
    prompt_truncation_side: "right"
    context_start_token: 0

alg:
  id: trpo
  args: 
    n_steps: 2
    verbose: 1
    learning_rate: 0.000001
    batch_size: 1
    n_critic_updates: 1


  kl_div:
    coeff: 0.1
    target_kl: 0.5
  policy:
    id: causal_lm_actor_critic_policy
    args:
      model_name: lvwerra/gpt2-imdb
      apply_model_parallel: True
      generation_kwargs:
        do_sample: True
        min_length: 20
        max_new_tokens: 20  
    
train_evaluation:
  # eval_batch_size: 100
  # eval_batch_size: 50
  eval_batch_size: 25
  n_iters: 100
  eval_every: 10
  save_every: 10
  metrics:
    - id: meteor
      args: {}
    - id: rouge
    - id: bleu
      args: {}
    - id: bert_score
      args:
        language: en
    # - id: bleurt
    #   args:
    #     config_name: bleurt-large-512
    - id: diversity
      args: {}
    # - id: summaCZS
    #   args:
    #     granularity: sentence
    #     use_ent: True
    #     use_con: False
    # - id: summaCConv
    #   args:
    #     granularity: sentence
  generation_kwargs: 
    do_sample: True
    top_k: 0
    temperature: 0.7
    min_length: 50
    # max_new_tokens: 100
    max_new_tokens: 50

