tokenizer:
  #model_name: t5-base t5-small
  model_name: Hydroflu/squad_t5_samll_ft
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: False

reward_fn:
  #id: cos_similarity
  id: bleu

datapool:
  id: squad
  #id: narrative_qa



env:
  #n_envs: 10
  n_envs: 2
  args:
    # max_prompt_length: 512
    # max_episode_length: 100
    # max_prompt_length: 256
    max_prompt_length: 128
    max_episode_length: 50
    terminate_on_eos: True
    prompt_truncation_side: "right"
    context_start_token: 0

 
alg:
  id: nlpo
  args:
    n_steps: 128
    batch_size: 32
    verbose: 1
    learning_rate: 0.000002
    n_epochs: 5
  kl_div:
    coeff: 0.001
    target_kl: 1.0
  policy:
    id: maskable_seq2seq_lm_actor_critic_policy
    args:
      model_name: Hydroflu/squad_t5_samll_ft
      apply_model_parallel: True
      mask_type: "learned_top_p"
      top_mask: 0.9
      target_update_iterations: 20
      generation_kwargs:
        do_sample: True
        top_k: 50



train_evaluation:
  # eval_batch_size: 100
  # eval_batch_size: 50
  eval_batch_size: 25
  n_iters: 100
  eval_every: 10
  save_every: 10
  metrics:
    - id: meteor
      args: {}
    - id: rouge
    - id: bleu
      args: {}
    - id: bert_score
      args:
        language: en
    # - id: bleurt
    #   args:
    #     config_name: bleurt-large-512
    - id: diversity
      args: {}
    # - id: summaCZS
    #   args:
    #     granularity: sentence
    #     use_ent: True
    #     use_con: False
    # - id: summaCConv
    #   args:
    #     granularity: sentence
  generation_kwargs: 
    do_sample: True
    top_k: 0
    temperature: 0.7
    min_length: 50
    # max_new_tokens: 100
    max_new_tokens: 50

